### ISSUE TITLE
nice project

### ISSUE THREAD

**Issue by BogusCurry** [thewarpaint/airport-dashboard#1]
Hi ;)

At first, yout airport-dashboard project is nice. I search long time a dashboard for a virtual airline. The dashboard must show the destinations from the virtual pilots. But the dashboard brought a backend for put the flys in the board. 

I am not a developer, so is difficult for me to code so a dashboard.

Greetings

Bogus

**Comment by thewarpaint** [comment]
Thanks! You can see a [preview of the dashboard here](http://thewarpaint.github.io/airport-dashboard/). I haven't decided on a license for this, but it's going to be open source, so feel free to do what you want with the code. Attribution is always appreciated!

**Comment by thewarpaint** [comment]
Also, there's going to be an API powering the UI, I'll work on it when I have time. The initial spec is here: https://github.com/thewarpaint/airport-api.
